# Generated by Django 5.1.7 on 2025-03-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=True, null=True, upload_to='media')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('composition', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('kilocalories', models.IntegerField()),
            ],
        ),
    ]
